#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BackButton

#include "Basic.hpp"

#include "BackButton_classes.hpp"
#include "BackButton_parameters.hpp"


namespace SDK
{

// Function BackButton.BackButton_C.ExecuteUbergraph_BackButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBackButton_C::ExecuteUbergraph_BackButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BackButton_C", "ExecuteUbergraph_BackButton");

	Params::BackButton_C_ExecuteUbergraph_BackButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BackButton.BackButton_C.BndEvt__Button_Selection_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBackButton_C::BndEvt__Button_Selection_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BackButton_C", "BndEvt__Button_Selection_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BackButton.BackButton_C.BP_TWFocusReceivedEvent
// (Event, Protected, BlueprintEvent)

void UBackButton_C::BP_TWFocusReceivedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BackButton_C", "BP_TWFocusReceivedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BackButton.BackButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBackButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BackButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

