#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterGhostAnimBP

#include "Basic.hpp"

#include "CharacterGhostAnimBP_classes.hpp"
#include "CharacterGhostAnimBP_parameters.hpp"


namespace SDK
{

// Function CharacterGhostAnimBP.CharacterGhostAnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UCharacterGhostAnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterGhostAnimBP_C", "AnimGraph");

	Params::CharacterGhostAnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function CharacterGhostAnimBP.CharacterGhostAnimBP_C.ExecuteUbergraph_CharacterGhostAnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCharacterGhostAnimBP_C::ExecuteUbergraph_CharacterGhostAnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterGhostAnimBP_C", "ExecuteUbergraph_CharacterGhostAnimBP");

	Params::CharacterGhostAnimBP_C_ExecuteUbergraph_CharacterGhostAnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

