#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Crosshair_Rifle

#include "Basic.hpp"

#include "Crosshair_Rifle_classes.hpp"
#include "Crosshair_Rifle_parameters.hpp"


namespace SDK
{

// Function Crosshair_Rifle.Crosshair_Rifle_C.ExecuteUbergraph_Crosshair_Rifle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCrosshair_Rifle_C::ExecuteUbergraph_Crosshair_Rifle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "ExecuteUbergraph_Crosshair_Rifle");

	Params::Crosshair_Rifle_C_ExecuteUbergraph_Crosshair_Rifle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.ShowHitFeedback
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              HitColor                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCrosshair_Rifle_C::ShowHitFeedback(const struct FLinearColor& HitColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "ShowHitFeedback");

	Params::Crosshair_Rifle_C_ShowHitFeedback Parms{};

	Parms.HitColor = std::move(HitColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.UpdateCrosshairColor
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   ColorIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCrosshair_Rifle_C::UpdateCrosshairColor(int32 ColorIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "UpdateCrosshairColor");

	Params::Crosshair_Rifle_C_UpdateCrosshairColor Parms{};

	Parms.ColorIndex = ColorIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCrosshair_Rifle_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "Tick");

	Params::Crosshair_Rifle_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.OnSpreadChanged
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Spread                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCrosshair_Rifle_C::OnSpreadChanged(float Spread)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "OnSpreadChanged");

	Params::Crosshair_Rifle_C_OnSpreadChanged Parms{};

	Parms.Spread = Spread;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCrosshair_Rifle_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Crosshair_Rifle.Crosshair_Rifle_C.SetImpactCrosshair
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCrosshair_Rifle_C::SetImpactCrosshair(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Crosshair_Rifle_C", "SetImpactCrosshair");

	Params::Crosshair_Rifle_C_SetImpactCrosshair Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}

}

