#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CyclicMovementComponent

#include "Basic.hpp"

#include "CyclicMovementComponent_classes.hpp"
#include "CyclicMovementComponent_parameters.hpp"


namespace SDK
{

// Function CyclicMovementComponent.CyclicMovementComponent_C.ExecuteUbergraph_CyclicMovementComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCyclicMovementComponent_C::ExecuteUbergraph_CyclicMovementComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CyclicMovementComponent_C", "ExecuteUbergraph_CyclicMovementComponent");

	Params::CyclicMovementComponent_C_ExecuteUbergraph_CyclicMovementComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CyclicMovementComponent.CyclicMovementComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCyclicMovementComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CyclicMovementComponent_C", "ReceiveTick");

	Params::CyclicMovementComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CyclicMovementComponent.CyclicMovementComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UCyclicMovementComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CyclicMovementComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CyclicMovementComponent.CyclicMovementComponent_C.UpdateMovement
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UCyclicMovementComponent_C::UpdateMovement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CyclicMovementComponent_C", "UpdateMovement");

	UObject::ProcessEvent(Func, nullptr);
}

}

