#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultSpinner_Override

#include "Basic.hpp"

#include "DefaultSpinner_Override_classes.hpp"
#include "DefaultSpinner_Override_parameters.hpp"


namespace SDK
{

// Function DefaultSpinner_Override.DefaultSpinner_Override_C.ExecuteUbergraph_DefaultSpinner_Override
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDefaultSpinner_Override_C::ExecuteUbergraph_DefaultSpinner_Override(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "ExecuteUbergraph_DefaultSpinner_Override");

	Params::DefaultSpinner_Override_C_ExecuteUbergraph_DefaultSpinner_Override Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefaultSpinner_Override.DefaultSpinner_Override_C.BndEvt__RightButton_K2Node_ComponentBoundEvent_196_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UDefaultSpinner_Override_C::BndEvt__RightButton_K2Node_ComponentBoundEvent_196_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "BndEvt__RightButton_K2Node_ComponentBoundEvent_196_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultSpinner_Override.DefaultSpinner_Override_C.BndEvt__LeftButton_K2Node_ComponentBoundEvent_178_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UDefaultSpinner_Override_C::BndEvt__LeftButton_K2Node_ComponentBoundEvent_178_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "BndEvt__LeftButton_K2Node_ComponentBoundEvent_178_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultSpinner_Override.DefaultSpinner_Override_C.GetLabelText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UDefaultSpinner_Override_C::GetLabelText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "GetLabelText");

	Params::DefaultSpinner_Override_C_GetLabelText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DefaultSpinner_Override.DefaultSpinner_Override_C.GetLeftArrowColorAndOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UDefaultSpinner_Override_C::GetLeftArrowColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "GetLeftArrowColorAndOpacity");

	Params::DefaultSpinner_Override_C_GetLeftArrowColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DefaultSpinner_Override.DefaultSpinner_Override_C.GetRightArrowColorAndOpacity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UDefaultSpinner_Override_C::GetRightArrowColorAndOpacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultSpinner_Override_C", "GetRightArrowColorAndOpacity");

	Params::DefaultSpinner_Override_C_GetRightArrowColorAndOpacity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

