#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultSpinnerSetting_Override

#include "Basic.hpp"

#include "AutoSettings_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DefaultSpinnerSetting_Override.DefaultSpinnerSetting_Override_C
// 0x0000 (0x02A8 - 0x02A8)
class UDefaultSpinnerSetting_Override_C final : public USpinnerSetting
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefaultSpinnerSetting_Override_C">();
	}
	static class UDefaultSpinnerSetting_Override_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultSpinnerSetting_Override_C>();
	}
};
static_assert(alignof(UDefaultSpinnerSetting_Override_C) == 0x000008, "Wrong alignment on UDefaultSpinnerSetting_Override_C");
static_assert(sizeof(UDefaultSpinnerSetting_Override_C) == 0x0002A8, "Wrong size on UDefaultSpinnerSetting_Override_C");

}

