#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultAxisMapping_Override

#include "Basic.hpp"

#include "DefaultAxisMapping_Override_classes.hpp"
#include "DefaultAxisMapping_Override_parameters.hpp"


namespace SDK
{

// Function DefaultAxisMapping_Override.DefaultAxisMapping_Override_C.ExecuteUbergraph_DefaultAxisMapping_Override
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDefaultAxisMapping_Override_C::ExecuteUbergraph_DefaultAxisMapping_Override(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultAxisMapping_Override_C", "ExecuteUbergraph_DefaultAxisMapping_Override");

	Params::DefaultAxisMapping_Override_C_ExecuteUbergraph_DefaultAxisMapping_Override Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefaultAxisMapping_Override.DefaultAxisMapping_Override_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDefaultAxisMapping_Override_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultAxisMapping_Override_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

