#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultActionLabel_Override

#include "Basic.hpp"

#include "AutoSettings_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DefaultActionLabel_Override.DefaultActionLabel_Override_C
// 0x0000 (0x02C8 - 0x02C8)
class UDefaultActionLabel_Override_C final : public UActionLabel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefaultActionLabel_Override_C">();
	}
	static class UDefaultActionLabel_Override_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultActionLabel_Override_C>();
	}
};
static_assert(alignof(UDefaultActionLabel_Override_C) == 0x000008, "Wrong alignment on UDefaultActionLabel_Override_C");
static_assert(sizeof(UDefaultActionLabel_Override_C) == 0x0002C8, "Wrong size on UDefaultActionLabel_Override_C");

}

