#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ExplodingBarrel_BP

#include "Basic.hpp"

#include "ExplodingBarrel_BP_classes.hpp"
#include "ExplodingBarrel_BP_parameters.hpp"


namespace SDK
{

// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.ExecuteUbergraph_ExplodingBarrel_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::ExecuteUbergraph_ExplodingBarrel_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "ExecuteUbergraph_ExplodingBarrel_BP");

	Params::ExplodingBarrel_BP_C_ExecuteUbergraph_ExplodingBarrel_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.Cosmetic_OnFuseTimestampChange
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// float                                   NewFuseTimestamp                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::Cosmetic_OnFuseTimestampChange(float NewFuseTimestamp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "Cosmetic_OnFuseTimestampChange");

	Params::ExplodingBarrel_BP_C_Cosmetic_OnFuseTimestampChange Parms{};

	Parms.NewFuseTimestamp = NewFuseTimestamp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFluxCapacitorStates                    OldState_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFluxCapacitorStates                    NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::CustomEvent(EFluxCapacitorStates OldState_0, EFluxCapacitorStates NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "CustomEvent");

	Params::ExplodingBarrel_BP_C_CustomEvent Parms{};

	Parms.OldState_0 = OldState_0;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.Cosmetic_UpdateExplosionFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// float                                   VisualExplosionFactor                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::Cosmetic_UpdateExplosionFX(float VisualExplosionFactor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "Cosmetic_UpdateExplosionFX");

	Params::ExplodingBarrel_BP_C_Cosmetic_UpdateExplosionFX Parms{};

	Parms.VisualExplosionFactor = VisualExplosionFactor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "ReceiveTick");

	Params::ExplodingBarrel_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AExplodingBarrel_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AExplodingBarrel_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.InitializeDynamicsMaterials
// (Public, BlueprintCallable, BlueprintEvent)

void AExplodingBarrel_BP_C::InitializeDynamicsMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "InitializeDynamicsMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.Construct_Particles
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AExplodingBarrel_BP_C::Construct_Particles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "Construct_Particles");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.OnStateChangeVisualupdate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFluxBarrelState                        OldState_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFluxBarrelState                        NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::OnStateChangeVisualupdate(EFluxBarrelState OldState_0, EFluxBarrelState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "OnStateChangeVisualupdate");

	Params::ExplodingBarrel_BP_C_OnStateChangeVisualupdate Parms{};

	Parms.OldState_0 = OldState_0;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ExplodingBarrel_BP.ExplodingBarrel_BP_C.FakeTimeDilationSound
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFluxCapacitorStates                    GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AExplodingBarrel_BP_C::FakeTimeDilationSound(EFluxCapacitorStates GameState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ExplodingBarrel_BP_C", "FakeTimeDilationSound");

	Params::ExplodingBarrel_BP_C_FakeTimeDilationSound Parms{};

	Parms.GameState = GameState;

	UObject::ProcessEvent(Func, &Parms);
}

}

