#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluxPlayerControllerBP

#include "Basic.hpp"

#include "FluxPlayerControllerBP_classes.hpp"
#include "FluxPlayerControllerBP_parameters.hpp"


namespace SDK
{

// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.ExecuteUbergraph_FluxPlayerControllerBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFluxPlayerControllerBP_C::ExecuteUbergraph_FluxPlayerControllerBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "ExecuteUbergraph_FluxPlayerControllerBP");

	Params::FluxPlayerControllerBP_C_ExecuteUbergraph_FluxPlayerControllerBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.BP_OnStandaloneGameResume
// (Event, Public, BlueprintEvent)

void AFluxPlayerControllerBP_C::BP_OnStandaloneGameResume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "BP_OnStandaloneGameResume");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.BP_OnStandaloneGamePause
// (Event, Public, BlueprintEvent)

void AFluxPlayerControllerBP_C::BP_OnStandaloneGamePause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "BP_OnStandaloneGamePause");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.Server_DeleteLocalData
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void AFluxPlayerControllerBP_C::Server_DeleteLocalData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "Server_DeleteLocalData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.Client_SendAccuracyData
// (Net, NetReliable, HasOutParams, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FWeaponImpactData>& NewParam                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void AFluxPlayerControllerBP_C::Client_SendAccuracyData(const TArray<struct FWeaponImpactData>& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "Client_SendAccuracyData");

	Params::FluxPlayerControllerBP_C_Client_SendAccuracyData Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.Server_RequestAccuracyData
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void AFluxPlayerControllerBP_C::Server_RequestAccuracyData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "Server_RequestAccuracyData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.BP_OnGameInitialized
// (Event, Public, BlueprintEvent)

void AFluxPlayerControllerBP_C::BP_OnGameInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "BP_OnGameInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.InpActEvt_QualityMax_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AFluxPlayerControllerBP_C::InpActEvt_QualityMax_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "InpActEvt_QualityMax_K2Node_InputActionEvent_0");

	Params::FluxPlayerControllerBP_C_InpActEvt_QualityMax_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.InpActEvt_QualityMin_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AFluxPlayerControllerBP_C::InpActEvt_QualityMin_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "InpActEvt_QualityMin_K2Node_InputActionEvent_1");

	Params::FluxPlayerControllerBP_C_InpActEvt_QualityMin_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function FluxPlayerControllerBP.FluxPlayerControllerBP_C.GetControlsWidgetContainer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNGDWidgetContainer*              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UNGDWidgetContainer* AFluxPlayerControllerBP_C::GetControlsWidgetContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FluxPlayerControllerBP_C", "GetControlsWidgetContainer");

	Params::FluxPlayerControllerBP_C_GetControlsWidgetContainer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

