#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeadBodyPartBP

#include "Basic.hpp"

#include "UnrealProject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HeadBodyPartBP.HeadBodyPartBP_C
// 0x0000 (0x0030 - 0x0030)
class UHeadBodyPartBP_C : public UNGDBodyPart
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HeadBodyPartBP_C">();
	}
	static class UHeadBodyPartBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeadBodyPartBP_C>();
	}
};
static_assert(alignof(UHeadBodyPartBP_C) == 0x000008, "Wrong alignment on UHeadBodyPartBP_C");
static_assert(sizeof(UHeadBodyPartBP_C) == 0x000030, "Wrong size on UHeadBodyPartBP_C");

}

