#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HS_CustomMatchLobby

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HS_CustomMatchLobby.HS_CustomMatchLobby_C
// 0x0000 (0x0278 - 0x0278)
class UHS_CustomMatchLobby_C final : public UHUDStateCustomMatchLobby
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HS_CustomMatchLobby_C">();
	}
	static class UHS_CustomMatchLobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHS_CustomMatchLobby_C>();
	}
};
static_assert(alignof(UHS_CustomMatchLobby_C) == 0x000008, "Wrong alignment on UHS_CustomMatchLobby_C");
static_assert(sizeof(UHS_CustomMatchLobby_C) == 0x000278, "Wrong size on UHS_CustomMatchLobby_C");

}

