#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HS_MainMenu

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HS_MainMenu.HS_MainMenu_C
// 0x0000 (0x0270 - 0x0270)
class UHS_MainMenu_C final : public UHUDStateMainMenu
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HS_MainMenu_C">();
	}
	static class UHS_MainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHS_MainMenu_C>();
	}
};
static_assert(alignof(UHS_MainMenu_C) == 0x000008, "Wrong alignment on UHS_MainMenu_C");
static_assert(sizeof(UHS_MainMenu_C) == 0x000270, "Wrong size on UHS_MainMenu_C");

}

