#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HS_Options

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HS_Options.HS_Options_C
// 0x0000 (0x0268 - 0x0268)
class UHS_Options_C final : public UHUDStateOptions
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HS_Options_C">();
	}
	static class UHS_Options_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHS_Options_C>();
	}
};
static_assert(alignof(UHS_Options_C) == 0x000008, "Wrong alignment on UHS_Options_C");
static_assert(sizeof(UHS_Options_C) == 0x000268, "Wrong size on UHS_Options_C");

}

