#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Level_TutorialDM

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Level_TutorialDM.Level_TutorialDM_C
// 0x0000 (0x0150 - 0x0150)
class ULevel_TutorialDM_C final : public UTWLevelEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Level_TutorialDM_C">();
	}
	static class ULevel_TutorialDM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULevel_TutorialDM_C>();
	}
};
static_assert(alignof(ULevel_TutorialDM_C) == 0x000008, "Wrong alignment on ULevel_TutorialDM_C");
static_assert(sizeof(ULevel_TutorialDM_C) == 0x000150, "Wrong size on ULevel_TutorialDM_C");

}

