#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MagicLeapImageTracker

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct MagicLeapImageTracker.MagicLeapImageTrackerTarget
// 0x00A0 (0x00A0 - 0x0000)
struct alignas(0x08) FMagicLeapImageTrackerTarget final
{
public:
	uint8                                         Pad_0[0xA0];                                       // 0x0000(0x00A0)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FMagicLeapImageTrackerTarget) == 0x000008, "Wrong alignment on FMagicLeapImageTrackerTarget");
static_assert(sizeof(FMagicLeapImageTrackerTarget) == 0x0000A0, "Wrong size on FMagicLeapImageTrackerTarget");

}

