#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenuGameMode

#include "Basic.hpp"


namespace SDK::Params
{

// Function MainMenuGameMode.MainMenuGameMode_C.ExecuteUbergraph_MainMenuGameMode
// 0x0010 (0x0010 - 0x0000)
struct MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimeWatchGameInstance*                 CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode) == 0x000008, "Wrong alignment on MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode");
static_assert(sizeof(MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode) == 0x000010, "Wrong size on MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode");
static_assert(offsetof(MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode, EntryPoint) == 0x000000, "Member 'MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode::EntryPoint' has a wrong offset!");
static_assert(offsetof(MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'MainMenuGameMode_C_ExecuteUbergraph_MainMenuGameMode::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");

}

