#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MatchClock

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MatchClock.MatchClock_C
// 0x0010 (0x02E0 - 0x02D0)
class UMatchClock_C final : public UTWMatchClockWidget
{
public:
	class UImage*                                 Image_ClockInnerCircle;                            // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_ClockOuterCircle;                            // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MatchClock_C">();
	}
	static class UMatchClock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMatchClock_C>();
	}
};
static_assert(alignof(UMatchClock_C) == 0x000008, "Wrong alignment on UMatchClock_C");
static_assert(sizeof(UMatchClock_C) == 0x0002E0, "Wrong size on UMatchClock_C");
static_assert(offsetof(UMatchClock_C, Image_ClockInnerCircle) == 0x0002D0, "Member 'UMatchClock_C::Image_ClockInnerCircle' has a wrong offset!");
static_assert(offsetof(UMatchClock_C, Image_ClockOuterCircle) == 0x0002D8, "Member 'UMatchClock_C::Image_ClockOuterCircle' has a wrong offset!");

}

