#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ParadoxicalExplosion_BP

#include "Basic.hpp"

#include "ParadoxicalExplosion_BP_classes.hpp"
#include "ParadoxicalExplosion_BP_parameters.hpp"


namespace SDK
{

// Function ParadoxicalExplosion_BP.ParadoxicalExplosion_BP_C.ExecuteUbergraph_ParadoxicalExplosion_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AParadoxicalExplosion_BP_C::ExecuteUbergraph_ParadoxicalExplosion_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ParadoxicalExplosion_BP_C", "ExecuteUbergraph_ParadoxicalExplosion_BP");

	Params::ParadoxicalExplosion_BP_C_ExecuteUbergraph_ParadoxicalExplosion_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ParadoxicalExplosion_BP.ParadoxicalExplosion_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AParadoxicalExplosion_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ParadoxicalExplosion_BP_C", "ReceiveTick");

	Params::ParadoxicalExplosion_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ParadoxicalExplosion_BP.ParadoxicalExplosion_BP_C.Cosmetic_Setup
// (Event, Public, BlueprintEvent)
// Parameters:
// class ATimeWatchCharacter*              ExplosionOwner                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AParadoxicalExplosion_BP_C::Cosmetic_Setup(class ATimeWatchCharacter* ExplosionOwner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ParadoxicalExplosion_BP_C", "Cosmetic_Setup");

	Params::ParadoxicalExplosion_BP_C_Cosmetic_Setup Parms{};

	Parms.ExplosionOwner = ExplosionOwner;

	UObject::ProcessEvent(Func, &Parms);
}

}

