#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pellet_Projectile

#include "Basic.hpp"

#include "Pellet_Projectile_classes.hpp"
#include "Pellet_Projectile_parameters.hpp"


namespace SDK
{

// Function Pellet_Projectile.Pellet_Projectile_C.ExecuteUbergraph_Pellet_Projectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APellet_Projectile_C::ExecuteUbergraph_Pellet_Projectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pellet_Projectile_C", "ExecuteUbergraph_Pellet_Projectile");

	Params::Pellet_Projectile_C_ExecuteUbergraph_Pellet_Projectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Pellet_Projectile.Pellet_Projectile_C.Native_CosmeticsOnImpact
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void APellet_Projectile_C::Native_CosmeticsOnImpact(const struct FHitResult& HitResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pellet_Projectile_C", "Native_CosmeticsOnImpact");

	Params::Pellet_Projectile_C_Native_CosmeticsOnImpact Parms{};

	Parms.HitResult = std::move(HitResult);

	UObject::ProcessEvent(Func, &Parms);
}

}

