#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReplayHUD_BP

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ReplayHUD_BP.ReplayHUD_BP_C
// 0x0000 (0x0528 - 0x0528)
class AReplayHUD_BP_C final : public ATWReplayHUD
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ReplayHUD_BP_C">();
	}
	static class AReplayHUD_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AReplayHUD_BP_C>();
	}
};
static_assert(alignof(AReplayHUD_BP_C) == 0x000008, "Wrong alignment on AReplayHUD_BP_C");
static_assert(sizeof(AReplayHUD_BP_C) == 0x000528, "Wrong size on AReplayHUD_BP_C");

}

