#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMG_Projectile

#include "Basic.hpp"

#include "SMG_Projectile_classes.hpp"
#include "SMG_Projectile_parameters.hpp"


namespace SDK
{

// Function SMG_Projectile.SMG_Projectile_C.ExecuteUbergraph_SMG_Projectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASMG_Projectile_C::ExecuteUbergraph_SMG_Projectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SMG_Projectile_C", "ExecuteUbergraph_SMG_Projectile");

	Params::SMG_Projectile_C_ExecuteUbergraph_SMG_Projectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SMG_Projectile.SMG_Projectile_C.Native_CosmeticsOnImpact
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ASMG_Projectile_C::Native_CosmeticsOnImpact(const struct FHitResult& HitResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SMG_Projectile_C", "Native_CosmeticsOnImpact");

	Params::SMG_Projectile_C_Native_CosmeticsOnImpact Parms{};

	Parms.HitResult = std::move(HitResult);

	UObject::ProcessEvent(Func, &Parms);
}

}

