#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandardButton

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass StandardButton.StandardButton_C
// 0x0000 (0x0AC0 - 0x0AC0)
class UStandardButton_C : public UTWStandardButtonWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StandardButton_C">();
	}
	static class UStandardButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandardButton_C>();
	}
};
static_assert(alignof(UStandardButton_C) == 0x000008, "Wrong alignment on UStandardButton_C");
static_assert(sizeof(UStandardButton_C) == 0x000AC0, "Wrong size on UStandardButton_C");

}

