#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TutorialEntrybutton

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TutorialEntrybutton.TutorialEntrybutton_C
// 0x0000 (0x1738 - 0x1738)
class UTutorialEntrybutton_C final : public UTWCustomizationButtonWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TutorialEntrybutton_C">();
	}
	static class UTutorialEntrybutton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorialEntrybutton_C>();
	}
};
static_assert(alignof(UTutorialEntrybutton_C) == 0x000008, "Wrong alignment on UTutorialEntrybutton_C");
static_assert(sizeof(UTutorialEntrybutton_C) == 0x001738, "Wrong size on UTutorialEntrybutton_C");

}

