#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Target_BP

#include "Basic.hpp"

#include "UnrealProject_structs.hpp"
#include "DummyStates_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.ExecuteUbergraph_Tutorial_Target_BP
// 0x01E8 (0x01E8 - 0x0000)
struct Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FNGDDamageEvent                        K2Node_Event_DamageEvent;                          // 0x0008(0x0040)(ConstParm)
	class AController*                            K2Node_Event_InstigatorController;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDummyStates                                  K2Node_CustomEvent_NewState;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATimeWatchGameState*                    K2Node_DynamicCast_AsTime_Watch_Game_State;        // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_1;               // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGameplayActive_ReturnValue;             // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATimeWatchGameState*                    K2Node_DynamicCast_AsTime_Watch_Game_State_1;      // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetCurrentTime_ReturnValue;               // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetCurrentTime_ReturnValue_1;             // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x00A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             K2Node_CustomEvent_HitData;                        // 0x00A8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_132[0x2];                                      // 0x0132(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x013C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0148(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0154(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0160(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0180(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0198(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_K2_GetVectorParameterValue_ReturnValue;   // 0x01B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x01C8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x01D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_2;          // 0x01E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01E6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP) == 0x000008, "Wrong alignment on Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP");
static_assert(sizeof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP) == 0x0001E8, "Wrong size on Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, EntryPoint) == 0x000000, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_Event_DamageEvent) == 0x000008, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_Event_DamageEvent' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_Event_InstigatorController) == 0x000048, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_Event_InstigatorController' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_Event_DamageCauser) == 0x000050, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_Event_DamageCauser' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_CustomEvent_NewState) == 0x000058, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_CustomEvent_NewState' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_GetGameState_ReturnValue) == 0x000060, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_Event_DeltaSeconds) == 0x000068, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_DynamicCast_AsTime_Watch_Game_State) == 0x000070, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_DynamicCast_AsTime_Watch_Game_State' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_DynamicCast_bSuccess) == 0x000078, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_GetGameState_ReturnValue_1) == 0x000080, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_GetGameState_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_IsGameplayActive_ReturnValue) == 0x000088, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_IsGameplayActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_DynamicCast_AsTime_Watch_Game_State_1) == 0x000090, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_DynamicCast_AsTime_Watch_Game_State_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_DynamicCast_bSuccess_1) == 0x000098, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_GetCurrentTime_ReturnValue) == 0x00009C, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_GetCurrentTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_GetCurrentTime_ReturnValue_1) == 0x0000A0, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_GetCurrentTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000A4, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0000A5, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0000A6, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x0000A7, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_CustomEvent_HitData) == 0x0000A8, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_CustomEvent_HitData' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_bBlockingHit) == 0x000130, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_bInitialOverlap) == 0x000131, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_Time) == 0x000134, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_Distance) == 0x000138, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_Location) == 0x00013C, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_ImpactPoint) == 0x000148, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_Normal) == 0x000154, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_ImpactNormal) == 0x000160, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_PhysMat) == 0x000170, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_HitActor) == 0x000178, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_HitComponent) == 0x000180, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_HitBoneName) == 0x000188, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_HitItem) == 0x000190, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_FaceIndex) == 0x000194, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_TraceStart) == 0x000198, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BreakHitResult_TraceEnd) == 0x0001A4, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x0001B0, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_K2_GetVectorParameterValue_ReturnValue) == 0x0001B8, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_K2_GetVectorParameterValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_Conv_VectorToLinearColor_ReturnValue) == 0x0001C8, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_Conv_VectorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0001D8, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_NotEqual_ByteByte_ReturnValue_2) == 0x0001E4, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_NotEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, K2Node_SwitchEnum_CmpSuccess) == 0x0001E5, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP, CallFunc_BooleanAND_ReturnValue) == 0x0001E6, "Member 'Tutorial_Target_BP_C_ExecuteUbergraph_Tutorial_Target_BP::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.OnProjectileImpact
// 0x0088 (0x0088 - 0x0000)
struct Tutorial_Target_BP_C_OnProjectileImpact final
{
public:
	struct FHitResult                             HitData;                                           // 0x0000(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Tutorial_Target_BP_C_OnProjectileImpact) == 0x000004, "Wrong alignment on Tutorial_Target_BP_C_OnProjectileImpact");
static_assert(sizeof(Tutorial_Target_BP_C_OnProjectileImpact) == 0x000088, "Wrong size on Tutorial_Target_BP_C_OnProjectileImpact");
static_assert(offsetof(Tutorial_Target_BP_C_OnProjectileImpact, HitData) == 0x000000, "Member 'Tutorial_Target_BP_C_OnProjectileImpact::HitData' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Tutorial_Target_BP_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Target_BP_C_ReceiveTick) == 0x000004, "Wrong alignment on Tutorial_Target_BP_C_ReceiveTick");
static_assert(sizeof(Tutorial_Target_BP_C_ReceiveTick) == 0x000004, "Wrong size on Tutorial_Target_BP_C_ReceiveTick");
static_assert(offsetof(Tutorial_Target_BP_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Tutorial_Target_BP_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.SetState
// 0x0001 (0x0001 - 0x0000)
struct Tutorial_Target_BP_C_SetState final
{
public:
	EDummyStates                                  NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Target_BP_C_SetState) == 0x000001, "Wrong alignment on Tutorial_Target_BP_C_SetState");
static_assert(sizeof(Tutorial_Target_BP_C_SetState) == 0x000001, "Wrong size on Tutorial_Target_BP_C_SetState");
static_assert(offsetof(Tutorial_Target_BP_C_SetState, NewState) == 0x000000, "Member 'Tutorial_Target_BP_C_SetState::NewState' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.BP_OnDeath
// 0x0050 (0x0050 - 0x0000)
struct Tutorial_Target_BP_C_BP_OnDeath final
{
public:
	struct FNGDDamageEvent                        DamageEvent;                                       // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class AController*                            InstigatorController;                              // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0048(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Target_BP_C_BP_OnDeath) == 0x000008, "Wrong alignment on Tutorial_Target_BP_C_BP_OnDeath");
static_assert(sizeof(Tutorial_Target_BP_C_BP_OnDeath) == 0x000050, "Wrong size on Tutorial_Target_BP_C_BP_OnDeath");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnDeath, DamageEvent) == 0x000000, "Member 'Tutorial_Target_BP_C_BP_OnDeath::DamageEvent' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnDeath, InstigatorController) == 0x000040, "Member 'Tutorial_Target_BP_C_BP_OnDeath::InstigatorController' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnDeath, DamageCauser) == 0x000048, "Member 'Tutorial_Target_BP_C_BP_OnDeath::DamageCauser' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.SetMaterials
// 0x0098 (0x0098 - 0x0000)
struct Tutorial_Target_BP_C_SetMaterials final
{
public:
	TMap<int32, class UMaterialInterface*>        NewParam;                                          // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor)
	TArray<class UMaterialInterface*>             CallFunc_Map_Values_Values;                        // 0x0050(0x0010)(ZeroConstructor, ReferenceParm)
	TArray<int32>                                 CallFunc_Map_Keys_Keys;                            // 0x0060(0x0010)(ZeroConstructor, ReferenceParm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Get_Item;                           // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     CallFunc_Array_Get_Item_1;                         // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Target_BP_C_SetMaterials) == 0x000008, "Wrong alignment on Tutorial_Target_BP_C_SetMaterials");
static_assert(sizeof(Tutorial_Target_BP_C_SetMaterials) == 0x000098, "Wrong size on Tutorial_Target_BP_C_SetMaterials");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, NewParam) == 0x000000, "Member 'Tutorial_Target_BP_C_SetMaterials::NewParam' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Map_Values_Values) == 0x000050, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Map_Keys_Keys) == 0x000060, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, Temp_int_Array_Index_Variable) == 0x000070, "Member 'Tutorial_Target_BP_C_SetMaterials::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Array_Length_ReturnValue) == 0x000074, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Array_Get_Item) == 0x000078, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Array_Get_Item_1) == 0x000080, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, Temp_int_Loop_Counter_Variable) == 0x000088, "Member 'Tutorial_Target_BP_C_SetMaterials::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Less_IntInt_ReturnValue) == 0x00008C, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_SetMaterials, CallFunc_Add_IntInt_ReturnValue) == 0x000090, "Member 'Tutorial_Target_BP_C_SetMaterials::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function Tutorial_Target_BP.Tutorial_Target_BP_C.BP_OnTakeDamage
// 0x0060 (0x0060 - 0x0000)
struct Tutorial_Target_BP_C_BP_OnTakeDamage final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FNGDDamageEvent                        DamageEvent;                                       // 0x0008(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class AController*                            EventInstigator;                                   // 0x0048(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0050(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ReturnValue;                                       // 0x0058(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Tutorial_Target_BP_C_BP_OnTakeDamage) == 0x000008, "Wrong alignment on Tutorial_Target_BP_C_BP_OnTakeDamage");
static_assert(sizeof(Tutorial_Target_BP_C_BP_OnTakeDamage) == 0x000060, "Wrong size on Tutorial_Target_BP_C_BP_OnTakeDamage");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnTakeDamage, Damage) == 0x000000, "Member 'Tutorial_Target_BP_C_BP_OnTakeDamage::Damage' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnTakeDamage, DamageEvent) == 0x000008, "Member 'Tutorial_Target_BP_C_BP_OnTakeDamage::DamageEvent' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnTakeDamage, EventInstigator) == 0x000048, "Member 'Tutorial_Target_BP_C_BP_OnTakeDamage::EventInstigator' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnTakeDamage, DamageCauser) == 0x000050, "Member 'Tutorial_Target_BP_C_BP_OnTakeDamage::DamageCauser' has a wrong offset!");
static_assert(offsetof(Tutorial_Target_BP_C_BP_OnTakeDamage, ReturnValue) == 0x000058, "Member 'Tutorial_Target_BP_C_BP_OnTakeDamage::ReturnValue' has a wrong offset!");

}

