#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TWCharacterGhostBP

#include "Basic.hpp"

#include "TWCharacterGhostBP_classes.hpp"
#include "TWCharacterGhostBP_parameters.hpp"


namespace SDK
{

// Function TWCharacterGhostBP.TWCharacterGhostBP_C.ExecuteUbergraph_TWCharacterGhostBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATWCharacterGhostBP_C::ExecuteUbergraph_TWCharacterGhostBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "ExecuteUbergraph_TWCharacterGhostBP");

	Params::TWCharacterGhostBP_C_ExecuteUbergraph_TWCharacterGhostBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.OnStateChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFluxCapacitorStates                    OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFluxCapacitorStates                    NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATWCharacterGhostBP_C::OnStateChange(EFluxCapacitorStates OldState, EFluxCapacitorStates NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "OnStateChange");

	Params::TWCharacterGhostBP_C_OnStateChange Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATWCharacterGhostBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "ReceiveTick");

	Params::TWCharacterGhostBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.DestroyParadox
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShouldDoAnimation                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATWCharacterGhostBP_C::DestroyParadox(bool bShouldDoAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "DestroyParadox");

	Params::TWCharacterGhostBP_C_DestroyParadox Parms{};

	Parms.bShouldDoAnimation = bShouldDoAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.Cosmetic_MimicCharacter
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// class ATimeWatchCharacter*              Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATWCharacterGhostBP_C::Cosmetic_MimicCharacter(class ATimeWatchCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "Cosmetic_MimicCharacter");

	Params::TWCharacterGhostBP_C_Cosmetic_MimicCharacter Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.DestroyAnim__UpdateFunc
// (BlueprintEvent)

void ATWCharacterGhostBP_C::DestroyAnim__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "DestroyAnim__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.DestroyAnim__FinishedFunc
// (BlueprintEvent)

void ATWCharacterGhostBP_C::DestroyAnim__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "DestroyAnim__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.OnFirearmUse
// (Public, BlueprintCallable, BlueprintEvent)

void ATWCharacterGhostBP_C::OnFirearmUse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "OnFirearmUse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.MarkForRewindDestruction
// (Public, BlueprintCallable, BlueprintEvent)

void ATWCharacterGhostBP_C::MarkForRewindDestruction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "MarkForRewindDestruction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TWCharacterGhostBP.TWCharacterGhostBP_C.SetGameTimeCreationTimeStamp
// (Public, BlueprintCallable, BlueprintEvent)

void ATWCharacterGhostBP_C::SetGameTimeCreationTimeStamp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWCharacterGhostBP_C", "SetGameTimeCreationTimeStamp");

	UObject::ProcessEvent(Func, nullptr);
}

}

