#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TWFunctionLibrary

#include "Basic.hpp"

#include "TWFunctionLibrary_classes.hpp"
#include "TWFunctionLibrary_parameters.hpp"


namespace SDK
{

// Function TWFunctionLibrary.TWFunctionLibrary_C.GetColorScheme
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayColorScheme*            TeamColorsOutlines                                     (Parm, OutParm)

void UTWFunctionLibrary_C::GetColorScheme(class UObject* __WorldContext, struct FGameplayColorScheme* TeamColorsOutlines)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("TWFunctionLibrary_C", "GetColorScheme");

	Params::TWFunctionLibrary_C_GetColorScheme Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (TeamColorsOutlines != nullptr)
		*TeamColorsOutlines = std::move(Parms.TeamColorsOutlines);
}


// Function TWFunctionLibrary.TWFunctionLibrary_C.GetChromaActionColor
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    Color                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UTWFunctionLibrary_C::GetChromaActionColor(class FName ActionName, class UObject* __WorldContext, struct FLinearColor* Color, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("TWFunctionLibrary_C", "GetChromaActionColor");

	Params::TWFunctionLibrary_C_GetChromaActionColor Parms{};

	Parms.ActionName = ActionName;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Color != nullptr)
		*Color = std::move(Parms.Color);

	if (Success != nullptr)
		*Success = Parms.Success;
}

}

