#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TWRewardPopupWidget

#include "Basic.hpp"

#include "TWRewardPopupWidget_classes.hpp"
#include "TWRewardPopupWidget_parameters.hpp"


namespace SDK
{

// Function TWRewardPopupWidget.TWRewardPopupWidget_C.ExecuteUbergraph_TWRewardPopupWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTWRewardPopupWidget_C::ExecuteUbergraph_TWRewardPopupWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWRewardPopupWidget_C", "ExecuteUbergraph_TWRewardPopupWidget");

	Params::TWRewardPopupWidget_C_ExecuteUbergraph_TWRewardPopupWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TWRewardPopupWidget.TWRewardPopupWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTWRewardPopupWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TWRewardPopupWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

