#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_DeathsSummary

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WC_DeathsSummary.WC_DeathsSummary_C
// 0x0000 (0x0260 - 0x0260)
class UWC_DeathsSummary_C final : public UWidgetContainerDeathsSummary
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WC_DeathsSummary_C">();
	}
	static class UWC_DeathsSummary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWC_DeathsSummary_C>();
	}
};
static_assert(alignof(UWC_DeathsSummary_C) == 0x000008, "Wrong alignment on UWC_DeathsSummary_C");
static_assert(sizeof(UWC_DeathsSummary_C) == 0x000260, "Wrong size on UWC_DeathsSummary_C");

}

