#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_DailyBoost

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WC_DailyBoost.WC_DailyBoost_C
// 0x0010 (0x0350 - 0x0340)
class UWC_DailyBoost_C final : public UWidgetContainerDailyBoost
{
public:
	class UImage*                                 Image_67;                                          // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Background;                                  // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WC_DailyBoost_C">();
	}
	static class UWC_DailyBoost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWC_DailyBoost_C>();
	}
};
static_assert(alignof(UWC_DailyBoost_C) == 0x000008, "Wrong alignment on UWC_DailyBoost_C");
static_assert(sizeof(UWC_DailyBoost_C) == 0x000350, "Wrong size on UWC_DailyBoost_C");
static_assert(offsetof(UWC_DailyBoost_C, Image_67) == 0x000340, "Member 'UWC_DailyBoost_C::Image_67' has a wrong offset!");
static_assert(offsetof(UWC_DailyBoost_C, Image_Background) == 0x000348, "Member 'UWC_DailyBoost_C::Image_Background' has a wrong offset!");

}

