#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_FluxStateIcon

#include "Basic.hpp"

#include "WC_FluxStateIcon_classes.hpp"
#include "WC_FluxStateIcon_parameters.hpp"


namespace SDK
{

// Function WC_FluxStateIcon.WC_FluxStateIcon_C.ExecuteUbergraph_WC_FluxStateIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_FluxStateIcon_C::ExecuteUbergraph_WC_FluxStateIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_FluxStateIcon_C", "ExecuteUbergraph_WC_FluxStateIcon");

	Params::WC_FluxStateIcon_C_ExecuteUbergraph_WC_FluxStateIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_FluxStateIcon.WC_FluxStateIcon_C.PlayCycleNameAnimation
// (Event, Protected, BlueprintEvent)

void UWC_FluxStateIcon_C::PlayCycleNameAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_FluxStateIcon_C", "PlayCycleNameAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WC_FluxStateIcon.WC_FluxStateIcon_C.PlayForwardAnimation
// (Event, Protected, BlueprintEvent)

void UWC_FluxStateIcon_C::PlayForwardAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_FluxStateIcon_C", "PlayForwardAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WC_FluxStateIcon.WC_FluxStateIcon_C.PlayReverseAnimation
// (Event, Protected, BlueprintEvent)

void UWC_FluxStateIcon_C::PlayReverseAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_FluxStateIcon_C", "PlayReverseAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

