#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_InGameActionPrompt

#include "Basic.hpp"

#include "WC_InGameActionPrompt_classes.hpp"
#include "WC_InGameActionPrompt_parameters.hpp"


namespace SDK
{

// Function WC_InGameActionPrompt.WC_InGameActionPrompt_C.ShowActionPrompt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NewActionName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      ActionText                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UWC_InGameActionPrompt_C::ShowActionPrompt(class FName NewActionName, const class FText& ActionText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_InGameActionPrompt_C", "ShowActionPrompt");

	Params::WC_InGameActionPrompt_C_ShowActionPrompt Parms{};

	Parms.NewActionName = NewActionName;
	Parms.ActionText = std::move(ActionText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_InGameActionPrompt.WC_InGameActionPrompt_C.HidePrompt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_InGameActionPrompt_C::HidePrompt(class FName ActionName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_InGameActionPrompt_C", "HidePrompt");

	Params::WC_InGameActionPrompt_C_HidePrompt Parms{};

	Parms.ActionName_0 = ActionName_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

