#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_MatchHistorySlot

#include "Basic.hpp"

#include "TimeWatch_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WC_MatchHistorySlot.WC_MatchHistorySlot_C
// 0x0008 (0x03C8 - 0x03C0)
class UWC_MatchHistorySlot_C final : public UWidgetContainerMatchHistorySlot
{
public:
	class UImage*                                 Image_60;                                          // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WC_MatchHistorySlot_C">();
	}
	static class UWC_MatchHistorySlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWC_MatchHistorySlot_C>();
	}
};
static_assert(alignof(UWC_MatchHistorySlot_C) == 0x000008, "Wrong alignment on UWC_MatchHistorySlot_C");
static_assert(sizeof(UWC_MatchHistorySlot_C) == 0x0003C8, "Wrong size on UWC_MatchHistorySlot_C");
static_assert(offsetof(UWC_MatchHistorySlot_C, Image_60) == 0x0003C0, "Member 'UWC_MatchHistorySlot_C::Image_60' has a wrong offset!");

}

