#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_PlayerMatchIntro

#include "Basic.hpp"

#include "WC_PlayerMatchIntro_classes.hpp"
#include "WC_PlayerMatchIntro_parameters.hpp"


namespace SDK
{

// Function WC_PlayerMatchIntro.WC_PlayerMatchIntro_C.ExecuteUbergraph_WC_PlayerMatchIntro
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_PlayerMatchIntro_C::ExecuteUbergraph_WC_PlayerMatchIntro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerMatchIntro_C", "ExecuteUbergraph_WC_PlayerMatchIntro");

	Params::WC_PlayerMatchIntro_C_ExecuteUbergraph_WC_PlayerMatchIntro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_PlayerMatchIntro.WC_PlayerMatchIntro_C.ShowPlayerCard
// (Event, Public, BlueprintEvent)
// Parameters:
// class AFluxPlayerState*                 NewPlayerState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_PlayerMatchIntro_C::ShowPlayerCard(class AFluxPlayerState* NewPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerMatchIntro_C", "ShowPlayerCard");

	Params::WC_PlayerMatchIntro_C_ShowPlayerCard Parms{};

	Parms.NewPlayerState = NewPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}

}

