#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_PlayerInfoDisplay

#include "Basic.hpp"

#include "WC_PlayerInfoDisplay_classes.hpp"
#include "WC_PlayerInfoDisplay_parameters.hpp"


namespace SDK
{

// Function WC_PlayerInfoDisplay.WC_PlayerInfoDisplay_C.ExecuteUbergraph_WC_PlayerInfoDisplay
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_PlayerInfoDisplay_C::ExecuteUbergraph_WC_PlayerInfoDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerInfoDisplay_C", "ExecuteUbergraph_WC_PlayerInfoDisplay");

	Params::WC_PlayerInfoDisplay_C_ExecuteUbergraph_WC_PlayerInfoDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_PlayerInfoDisplay.WC_PlayerInfoDisplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWC_PlayerInfoDisplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerInfoDisplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WC_PlayerInfoDisplay.WC_PlayerInfoDisplay_C.Get_Image_Latency_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWC_PlayerInfoDisplay_C::Get_Image_Latency_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerInfoDisplay_C", "Get_Image_Latency_Visibility_0");

	Params::WC_PlayerInfoDisplay_C_Get_Image_Latency_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WC_PlayerInfoDisplay.WC_PlayerInfoDisplay_C.Get_Energy_Percent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWC_PlayerInfoDisplay_C::Get_Energy_Percent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_PlayerInfoDisplay_C", "Get_Energy_Percent_0");

	Params::WC_PlayerInfoDisplay_C_Get_Energy_Percent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

