#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_ReplayState

#include "Basic.hpp"


namespace SDK::Params
{

// Function WC_ReplayState.WC_ReplayState_C.ExecuteUbergraph_WC_ReplayState
// 0x0010 (0x0010 - 0x0000)
struct WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState) == 0x000008, "Wrong alignment on WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState");
static_assert(sizeof(WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState) == 0x000010, "Wrong size on WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState");
static_assert(offsetof(WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState, EntryPoint) == 0x000000, "Member 'WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState::EntryPoint' has a wrong offset!");
static_assert(offsetof(WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'WC_ReplayState_C_ExecuteUbergraph_WC_ReplayState::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

