#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_RewardTrack

#include "Basic.hpp"

#include "WC_RewardTrack_classes.hpp"
#include "WC_RewardTrack_parameters.hpp"


namespace SDK
{

// Function WC_RewardTrack.WC_RewardTrack_C.ExecuteUbergraph_WC_RewardTrack
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_RewardTrack_C::ExecuteUbergraph_WC_RewardTrack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_RewardTrack_C", "ExecuteUbergraph_WC_RewardTrack");

	Params::WC_RewardTrack_C_ExecuteUbergraph_WC_RewardTrack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_RewardTrack.WC_RewardTrack_C.UpdateRemainingTime
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   RemainingMinutes                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_RewardTrack_C::UpdateRemainingTime(int32 RemainingMinutes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_RewardTrack_C", "UpdateRemainingTime");

	Params::WC_RewardTrack_C_UpdateRemainingTime Parms{};

	Parms.RemainingMinutes = RemainingMinutes;

	UObject::ProcessEvent(Func, &Parms);
}

}

