#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_TipNotification

#include "Basic.hpp"

#include "WC_TipNotification_classes.hpp"
#include "WC_TipNotification_parameters.hpp"


namespace SDK
{

// Function WC_TipNotification.WC_TipNotification_C.ExecuteUbergraph_WC_TipNotification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_TipNotification_C::ExecuteUbergraph_WC_TipNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_TipNotification_C", "ExecuteUbergraph_WC_TipNotification");

	Params::WC_TipNotification_C_ExecuteUbergraph_WC_TipNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_TipNotification.WC_TipNotification_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_TipNotification_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_TipNotification_C", "Tick");

	Params::WC_TipNotification_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_TipNotification.WC_TipNotification_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWC_TipNotification_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_TipNotification_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

