#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WC_WeaponCustomization

#include "Basic.hpp"

#include "WC_WeaponCustomization_classes.hpp"
#include "WC_WeaponCustomization_parameters.hpp"


namespace SDK
{

// Function WC_WeaponCustomization.WC_WeaponCustomization_C.ExecuteUbergraph_WC_WeaponCustomization
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWC_WeaponCustomization_C::ExecuteUbergraph_WC_WeaponCustomization(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_WeaponCustomization_C", "ExecuteUbergraph_WC_WeaponCustomization");

	Params::WC_WeaponCustomization_C_ExecuteUbergraph_WC_WeaponCustomization Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WC_WeaponCustomization.WC_WeaponCustomization_C.BP_OnBuyItemSuccess
// (Event, Protected, BlueprintEvent)

void UWC_WeaponCustomization_C::BP_OnBuyItemSuccess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WC_WeaponCustomization_C", "BP_OnBuyItemSuccess");

	UObject::ProcessEvent(Func, nullptr);
}

}

