#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_GrenadeLauncher_Rocket

#include "Basic.hpp"

#include "Weapon_GrenadeLauncher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_GrenadeLauncher_Rocket.Weapon_GrenadeLauncher_Rocket_C
// 0x0000 (0x0B50 - 0x0B50)
class AWeapon_GrenadeLauncher_Rocket_C final : public AWeapon_GrenadeLauncher_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_GrenadeLauncher_Rocket_C">();
	}
	static class AWeapon_GrenadeLauncher_Rocket_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_GrenadeLauncher_Rocket_C>();
	}
};
static_assert(alignof(AWeapon_GrenadeLauncher_Rocket_C) == 0x000010, "Wrong alignment on AWeapon_GrenadeLauncher_Rocket_C");
static_assert(sizeof(AWeapon_GrenadeLauncher_Rocket_C) == 0x000B50, "Wrong size on AWeapon_GrenadeLauncher_Rocket_C");

}

