#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponAccuracyTest

#include "Basic.hpp"

#include "WeaponAccuracyTest_classes.hpp"
#include "WeaponAccuracyTest_parameters.hpp"


namespace SDK
{

// Function WeaponAccuracyTest.WeaponAccuracyTest_C.ExecuteUbergraph_WeaponAccuracyTest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWeaponAccuracyTest_C::ExecuteUbergraph_WeaponAccuracyTest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "ExecuteUbergraph_WeaponAccuracyTest");

	Params::WeaponAccuracyTest_C_ExecuteUbergraph_WeaponAccuracyTest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.RequestPartialTestData
// (BlueprintCallable, BlueprintEvent)

void AWeaponAccuracyTest_C::RequestPartialTestData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "RequestPartialTestData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.OnAccuracyDataReceived
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FWeaponImpactData>& OtherData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void AWeaponAccuracyTest_C::OnAccuracyDataReceived(const TArray<struct FWeaponImpactData>& OtherData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "OnAccuracyDataReceived");

	Params::WeaponAccuracyTest_C_OnAccuracyDataReceived Parms{};

	Parms.OtherData = std::move(OtherData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.ClearLocalImpactsData
// (BlueprintCallable, BlueprintEvent)

void AWeaponAccuracyTest_C::ClearLocalImpactsData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "ClearLocalImpactsData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.OnReceivedImpact
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ProjectileIndex                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                ImpactData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AWeaponAccuracyTest_C::OnReceivedImpact(int32 ProjectileIndex, const struct FHitResult& ImpactData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "OnReceivedImpact");

	Params::WeaponAccuracyTest_C_OnReceivedImpact Parms{};

	Parms.ProjectileIndex = ProjectileIndex;
	Parms.ImpactData = std::move(ImpactData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWeaponAccuracyTest_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "ReceiveTick");

	Params::WeaponAccuracyTest_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.InpActEvt_T_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AWeaponAccuracyTest_C::InpActEvt_T_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "InpActEvt_T_K2Node_InputKeyEvent_0");

	Params::WeaponAccuracyTest_C_InpActEvt_T_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.Diff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FWeaponImpactData>&       Other                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void AWeaponAccuracyTest_C::Diff(TArray<struct FWeaponImpactData>& Other)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "Diff");

	Params::WeaponAccuracyTest_C_Diff Parms{};

	Parms.Other = std::move(Other);

	UObject::ProcessEvent(Func, &Parms);

	Other = std::move(Parms.Other);
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.GetCurrentWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ATemporalWeapon**                 Weapon                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWeaponAccuracyTest_C::GetCurrentWeapon(class ATemporalWeapon** Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "GetCurrentWeapon");

	Params::WeaponAccuracyTest_C_GetCurrentWeapon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Weapon != nullptr)
		*Weapon = Parms.Weapon;
}


// Function WeaponAccuracyTest.WeaponAccuracyTest_C.PrintTestResult
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AWeaponAccuracyTest_C::PrintTestResult()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponAccuracyTest_C", "PrintTestResult");

	UObject::ProcessEvent(Func, nullptr);
}

}

